# HTTPS auth with OIDC
kind: Deployment
apiVersion: apps/v1
metadata:
  name: darker
  labels:
    app: cats
    type: darker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cats
      type: darker
  template:
    metadata:
      labels:
        app: cats
        type: darker
    spec:
      containers:
        - name: cats
          image: unfor19/docker-cats:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 128Mi
          env:
            - name: APP_NAME
              value: dark
            - name: FROM_AUTHOR              
              value: darker
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-credentials
                  key: google_client_id        
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: darker
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 80
  selector:
    app: cats
    type: darker
---
apiVersion: networking.k8s.io/v1beta1 # NGINX Ingress Controller supports this version
kind: Ingress
metadata:
  name: darker
  annotations:
    cert-manager.io/cluster-issuer: tls-ca-issuer # https://cert-manager.io/docs/usage/ingress/  
    nginx.ingress.kubernetes.io/auth-url: https://oidc.kubemaster.me/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://oidc.kubemaster.me/oauth2/start?rd=https://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization, X-Auth-Request-User, X-Auth-Request-Email, X-Auth-Request-Preferred-Username, X-Auth-Request-Access-Token"
spec:
  tls:
  - hosts:
    - darker.kubemaster.me
    secretName: darker-tls-secret
  ingressClassName: nginx
  rules:
    - host: darker.kubemaster.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: darker
              servicePort: 80
